### ISSUE TITLE
problems with DomAdapter

### ISSUE THREAD

**Issue by PatrickJS** [IgorMinar/new-world-test#10]
it seems like the DomAdapter api changed in this build compared to the angular repo

see universal PR https://github.com/IgorMinar/new-world-test/pull/9

**Comment by IgorMinar** [comment]
there were some small changes. the biggest one was that we export a getter function for the DOM adapter rather than the dom adapter itself.

I believe that the dom adapter should be kept private and universal should use a parse5 renderer rather than go through the dom adapter. 

@mhevery should weigh in on this one.

**Comment by naomiblack** [comment]
Patrick says he's unblocked now.
